EndPoint/Controllers/PlanController.cs
using EndPoint.Models.DomainModels.PlanAggregates;
using EndPoint.Models.Frameworks.Contract;
using Microsoft.AspNetCore.Mvc;
using System.Numerics;

namespace EndPoint.Controllers
{
    public class PlanController : Controller
    {

        #region [-Ctor()-]
        private readonly IPlanRepository _planRepository;
        public PlanController(IPlanRepository planRepository)
        {
            _planRepository=planRepository;
        }
        #endregion

        #region [-Index()-]
        public async Task<IActionResult> Index()
        {
            return View(await _planRepository.Select());
        }
        #endregion

        #region [-Create()-]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(long Id, [Bind("Time", "DayOfWeek", "Detail")] Plan plan)
        {
            if (ModelState.IsValid)
            {
                await _planRepository.Insert(plan);
                return RedirectToAction(nameof(Index));
            }
            return View(plan);
        }
        #endregion

        #region [-Delete()-]

        [HttpGet]
        public async Task<IActionResult> Delete(long id)
        {
            return View(await _planRepository.GetByIdAsync(id));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Plan plan)
        {
            await _planRepository.Delete(plan);
            return RedirectToAction("Index");
        }

        #endregion

        #region [-Update()-]

        [HttpGet]
        public async Task<IActionResult> Update(DayOfWeek day)
        {
            return View(await _planRepository.GetByDayAsync(day));
        }

        [HttpPost]
        public async Task<IActionResult> Update(List<Plan> plans)
        {
            if (ModelState.IsValid)
            {
                foreach (var plan in plans)
                {
                    await _planRepository.Update(plan);
                }
                return RedirectToAction("Index");
            }
            return View(plans);
        }
        #endregion

        #region [-Details()-]

        public async Task<IActionResult> Details(DayOfWeek day)
        {
            return View(await _planRepository.GetByDayAsync(day));
        }
        #endregion
    }
}

EndPoint/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/main.css" rel="stylesheet" />
    <link href="~/Content/css/util.css" rel="stylesheet" />
    <link href="~/Content/fonts/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/vendor/animate/animate.css" rel="stylesheet" />
    <link href="~/Content/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" />
    <link href="~/Content/vendor/select2/select2.min.css" rel="stylesheet" />
    <link href="~/Content/vendor/animate/animate.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Daily-Routine", "Index", "Plan", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="~/Content/vendor/jquery/jquery-3.2.1.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Content/js/main.js"></script>
    <script src="~/Content/vendor/select2/select2.min.js"></script>
</body>

@RenderSection("Scripts", false)
</html>